version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 3
  groups:
    szl-minor-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
      exclude-patterns:
      - torch*
      - transformers
      - accelerate
      - vllm
      - unsloth*
      - openai
- package-ecosystem: pip
  directories:
  - /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
    semver-major-days: 21
    semver-minor-days: 7
    semver-patch-days: 3
  groups:
    szl-minor-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
      exclude-patterns:
      - torch*
      - transformers
      - accelerate
      - vllm
      - unsloth*
      - openai
